nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: Joke API
            description: Simple Joke API that will fetch jokes for you.
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api
